/**
 * Đảm bảo schema và bảng MBTI tồn tại.
 * Standalone: tạo database nếu chưa có (3D000), sau đó chạy schema.sql.
 * Embedded (AI Portal): chỉ tạo schema riêng (mbti_career) trong DB của Portal.
 */
import pg from "pg";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { RUN_MODE, DATABASE_URL, DB_SCHEMA } from "./env.js";
import { resetPool } from "./db.js";

const { Pool } = pg;
const CODE_DB_DOES_NOT_EXIST = "3D000";

function extractDatabaseNameFromUrl(conn) {
  try {
    const u = new URL(conn.replace(/^postgresql:/i, "http:").replace(/^postgres:/i, "http:"));
    const p = u.pathname.replace(/^\//, "");
    if (!p) return null;
    return decodeURIComponent(p.split("/")[0]);
  } catch {
    return null;
  }
}

function withDatabaseName(conn, database) {
  const u = new URL(conn.replace(/^postgresql:/i, "http:").replace(/^postgres:/i, "http:"));
  u.pathname = "/" + encodeURIComponent(database);
  const proto = /^postgres:\/\//i.test(conn) ? "postgres:" : "postgresql:";
  return proto + u.href.slice("http:".length);
}

function quoteDbNameForCreate(name) {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
    throw new Error(
      `Tên database "${name}" không hỗ trợ tự tạo (chỉ chữ, số, _). Hãy tạo DB thủ công: createdb ${name}`,
    );
  }
  return '"' + name.replace(/"/g, '""') + '"';
}

async function createStandaloneDatabaseIfMissing() {
  if (RUN_MODE !== "standalone" || !DATABASE_URL) return;

  const probe = new Pool({ connectionString: DATABASE_URL, max: 1, connectionTimeoutMillis: 10_000 });
  try {
    await probe.query("SELECT 1");
    return;
  } catch (e) {
    const code = e?.code;
    if (code !== CODE_DB_DOES_NOT_EXIST) throw e;
  } finally {
    await probe.end().catch(() => {});
  }

  const dbName = extractDatabaseNameFromUrl(DATABASE_URL);
  if (!dbName) throw new Error("[mbti-ensure-db] Không đọc được tên database từ DATABASE_URL");
  const quoted = quoteDbNameForCreate(dbName);

  let lastErr = null;
  for (const adminDb of ["postgres", "template1"]) {
    const adminUrl = withDatabaseName(DATABASE_URL, adminDb);
    const adminPool = new Pool({ connectionString: adminUrl, max: 1, connectionTimeoutMillis: 10_000 });
    try {
      await adminPool.query(`CREATE DATABASE ${quoted}`);
      console.log("[mbti-ensure-db] Đã tạo database PostgreSQL:", dbName);
      await adminPool.end();
      resetPool();
      return;
    } catch (err) {
      await adminPool.end().catch(() => {});
      const code = err?.code;
      if (code === "42P04") {
        console.log("[mbti-ensure-db] Database đã tồn tại:", dbName);
        resetPool();
        return;
      }
      lastErr = err;
    }
  }
  throw lastErr ?? new Error("CREATE DATABASE thất bại");
}

const EMBEDDED_DEFAULT_SCHEMA = `
CREATE SCHEMA IF NOT EXISTS __SCHEMA__;

CREATE TABLE IF NOT EXISTS __SCHEMA__.mbti_types (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(4) NOT NULL UNIQUE
);

INSERT INTO __SCHEMA__.mbti_types (id, code) VALUES
  (1,'INTJ'),(2,'INTP'),(3,'ENTJ'),(4,'ENTP'),(5,'INFJ'),(6,'INFP'),(7,'ENFJ'),(8,'ENFP'),
  (9,'ISTJ'),(10,'ISFJ'),(11,'ESTJ'),(12,'ESFJ'),(13,'ISTP'),(14,'ISFP'),(15,'ESTP'),(16,'ESFP')
ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS __SCHEMA__.mbti_sessions (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name       text NOT NULL,
  user_profile_id text NOT NULL,
  mbti_result     varchar(4) NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS __SCHEMA__.mbti_answers (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id      bigint NOT NULL REFERENCES __SCHEMA__.mbti_sessions(id) ON DELETE CASCADE,
  question_number int NOT NULL,
  answer_value    int NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, question_number)
);

CREATE TABLE IF NOT EXISTS __SCHEMA__.ai_consultations (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id      bigint NOT NULL REFERENCES __SCHEMA__.mbti_sessions(id) ON DELETE CASCADE,
  mbti_result     varchar(4) NOT NULL,
  provider        text NOT NULL,
  consultation    text,
  sections        jsonb,
  object_name     text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
`;

function getSchemaContent() {
  const distDir = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    path.join(distDir, "..", "schema", "schema.sql"),
    path.join(distDir, "..", "..", "schema", "schema.sql"),
    path.join(process.cwd(), "schema", "schema.sql"),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return fs.readFileSync(p, "utf-8");
  }
  if (RUN_MODE === "embedded") return EMBEDDED_DEFAULT_SCHEMA;
  return null;
}

async function schemaAlreadyApplied() {
  const { query } = await import("./db.js");
  const r = await query(
    `SELECT 1 AS n FROM information_schema.tables WHERE table_schema = $1 AND table_name = 'mbti_sessions'`,
    [DB_SCHEMA],
  );
  return (r?.rows?.length ?? 0) > 0;
}

async function ensureMigrations() {
  const { query } = await import("./db.js");
  const r = await query(
    `SELECT 1 AS n FROM information_schema.tables WHERE table_schema = $1 AND table_name = 'ai_consultations'`,
    [DB_SCHEMA],
  );
  if ((r?.rows?.length ?? 0) === 0) {
    await query(`
      CREATE TABLE IF NOT EXISTS __SCHEMA__.ai_consultations (
        id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id      bigint NOT NULL REFERENCES __SCHEMA__.mbti_sessions(id) ON DELETE CASCADE,
        mbti_result     varchar(4) NOT NULL,
        provider        text NOT NULL,
        consultation    text,
        sections        jsonb,
        object_name     text,
        created_at      timestamptz NOT NULL DEFAULT now()
      )
    `);
    await query(
      `CREATE INDEX IF NOT EXISTS idx_mbti_ai_consultations_session_id ON __SCHEMA__.ai_consultations(session_id)`,
    );
    console.log("[mbti-ensure-db] Migration: ai_consultations table created");
  }
}

async function applySchema() {
  const sqlRaw = getSchemaContent();
  if (!sqlRaw?.trim()) {
    console.warn("[mbti-ensure-db] schema/schema.sql không tìm thấy, bỏ qua");
    return;
  }
  const quoted = `"${DB_SCHEMA}"`;
  const sql = sqlRaw.replace(/__SCHEMA__/g, quoted);
  const statements = sql
    .split(/;\s*\n/)
    .map((s) => s.replace(/^\s*--[^\n]*\n?/gm, "").trim())
    .filter(Boolean);
  const pool = new Pool({ connectionString: DATABASE_URL, max: 1 });
  try {
    for (const stmt of statements) {
      const s = stmt.endsWith(";") ? stmt : stmt + ";";
      try {
        await pool.query(s);
      } catch (stmtErr) {
        const code = stmtErr?.code;
        if (code === "23505" || code === "42P06") continue;
        throw stmtErr;
      }
    }
    console.log("[mbti-ensure-db] Schema", DB_SCHEMA, "applied");
  } finally {
    await pool.end();
  }
}

export async function ensureDatabase() {
  if (!DATABASE_URL) {
    console.warn("[mbti-ensure-db] No DATABASE_URL, skip");
    return;
  }
  try {
    if (RUN_MODE === "standalone") await createStandaloneDatabaseIfMissing();
    if (!(await schemaAlreadyApplied())) {
      console.log("[mbti-ensure-db] Applying schema...");
      await applySchema();
    } else {
      await ensureMigrations();
    }
  } catch (err) {
    console.error("[mbti-ensure-db] Error:", err?.message || err);
    throw err;
  }
}
