-- Chạy một lần trên database của AI Portal để tạo schema mbti_career (khi app embedded chưa tự tạo được).
-- Ví dụ: docker exec -i aiportal-postgres psql -U postgres -d postgres -f - < backend/schema/embed-init.sql
-- Hoặc:  psql -h localhost -U postgres -d postgres -f backend/schema/embed-init.sql

CREATE SCHEMA IF NOT EXISTS mbti_career;

CREATE TABLE IF NOT EXISTS mbti_career.mbti_types (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(4) NOT NULL UNIQUE
);

INSERT INTO mbti_career.mbti_types (id, code) VALUES
  (1,  'INTJ'), (2,  'INTP'), (3,  'ENTJ'), (4,  'ENTP'),
  (5,  'INFJ'), (6,  'INFP'), (7,  'ENFJ'), (8,  'ENFP'),
  (9,  'ISTJ'), (10, 'ISFJ'), (11, 'ESTJ'), (12, 'ESFJ'),
  (13, 'ISTP'), (14, 'ISFP'), (15, 'ESTP'), (16, 'ESFP')
ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS mbti_career.mbti_sessions (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name       text NOT NULL,
  user_profile_id text NOT NULL,
  mbti_result     varchar(4) NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mbti_sessions_created_at ON mbti_career.mbti_sessions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mbti_sessions_mbti_result ON mbti_career.mbti_sessions(mbti_result);
CREATE INDEX IF NOT EXISTS idx_mbti_sessions_user_profile_id ON mbti_career.mbti_sessions(user_profile_id);

CREATE TABLE IF NOT EXISTS mbti_career.mbti_answers (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id      bigint NOT NULL REFERENCES mbti_career.mbti_sessions(id) ON DELETE CASCADE,
  question_number int NOT NULL,
  answer_value    int NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, question_number)
);

CREATE TABLE IF NOT EXISTS mbti_career.ai_consultations (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id      bigint NOT NULL REFERENCES mbti_career.mbti_sessions(id) ON DELETE CASCADE,
  mbti_result     varchar(4) NOT NULL,
  provider        text NOT NULL,
  consultation    text,
  sections        jsonb,
  object_name     text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mbti_ai_consultations_session_id ON mbti_career.ai_consultations(session_id);
