-- MBTI Career NEU: __SCHEMA__ được thay bằng tên schema (ví dụ "mbti_career") khi chạy
CREATE SCHEMA IF NOT EXISTS __SCHEMA__;

-- 16 nhóm MBTI tham chiếu
CREATE TABLE IF NOT EXISTS __SCHEMA__.mbti_types (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(4) NOT NULL UNIQUE
);

INSERT INTO __SCHEMA__.mbti_types (id, code) VALUES
  (1,  'INTJ'), (2,  'INTP'), (3,  'ENTJ'), (4,  'ENTP'),
  (5,  'INFJ'), (6,  'INFP'), (7,  'ENFJ'), (8,  'ENFP'),
  (9,  'ISTJ'), (10, 'ISFJ'), (11, 'ESTJ'), (12, 'ESFJ'),
  (13, 'ISTP'), (14, 'ISFP'), (15, 'ESTP'), (16, 'ESFP')
ON CONFLICT (code) DO NOTHING;

-- Một lần làm bài của người dùng
CREATE TABLE IF NOT EXISTS __SCHEMA__.mbti_sessions (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name       text NOT NULL,
  user_profile_id text NOT NULL,
  mbti_result     varchar(4) NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mbti_sessions_created_at ON __SCHEMA__.mbti_sessions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mbti_sessions_mbti_result ON __SCHEMA__.mbti_sessions(mbti_result);
CREATE INDEX IF NOT EXISTS idx_mbti_sessions_user_profile_id ON __SCHEMA__.mbti_sessions(user_profile_id);

-- 20 câu trả lời cho từng session
CREATE TABLE IF NOT EXISTS __SCHEMA__.mbti_answers (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id      bigint NOT NULL REFERENCES __SCHEMA__.mbti_sessions(id) ON DELETE CASCADE,
  question_number int NOT NULL,
  answer_value    int NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, question_number)
);

-- Kết quả tư vấn AI theo từng session: lưu nguyên text + JSON 7 mục đã bóc tách + provider
CREATE TABLE IF NOT EXISTS __SCHEMA__.ai_consultations (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id      bigint NOT NULL REFERENCES __SCHEMA__.mbti_sessions(id) ON DELETE CASCADE,
  mbti_result     varchar(4) NOT NULL,
  provider        text NOT NULL,
  consultation    text,
  sections        jsonb,
  object_name     text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mbti_ai_consultations_session_id ON __SCHEMA__.ai_consultations(session_id);
