CREATE TABLE IF NOT EXISTS mbti_types (
  id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(4) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mbti_sessions (
  id biginteger GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name text NOT NULL,
  user_profile_id text NOT NULL,
  mbti_result varchar(4) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mbti_answers (
  id biginteger GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL REFERENCES mbti_sessions(id) ON DELETE CASCADE,
  question_number int NOT NULL,
  answer_value int NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, question_number)
);

CREATE TABLE IF NOT EXISTS programs (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    major_code VARCHAR(20),     -- mã ngành
    admission_code VARCHAR(20), -- mã xét tuyển
    description TEXT
);

CREATE TABLE IF NOT EXISTS careers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    description TEXT
);

CREATE TABLE IF NOT EXISTS mbti_programs (
    mbti_id INT REFERENCES mbti_types(id),
    program_id INT REFERENCES programs(id),
    fit_score INT,
    PRIMARY KEY (mbti_id, program_id)
);

CREATE TABLE IF NOT EXISTS mbti_program_careers (
    mbti_id INT REFERENCES mbti_types(id),
    program_id INT REFERENCES programs(id),
    career_id INT REFERENCES careers(id),
    fit_score INT,
    PRIMARY KEY (mbti_id, program_id, career_id)
);

CREATE TABLE IF NOT EXISTS program_careers (
    program_id INT REFERENCES programs(id),
    career_id INT REFERENCES careers(id),
    PRIMARY KEY (program_id, career_id)
);


INSERT INTO mbti_types (id, code) VALUES
  (1,  'INTJ'),
  (2,  'INTP'),
  (3,  'ENTJ'),
  (4,  'ENTP'),
  (5,  'INFJ'),
  (6,  'INFP'),
  (7,  'ENFJ'),
  (8,  'ENFP'),
  (9,  'ISTJ'),
  (10, 'ISFJ'),
  (11, 'ESTJ'),
  (12, 'ESFJ'),
  (13, 'ISTP'),
  (14, 'ISFP'),
  (15, 'ESTP'),
  (16, 'ESFP')
ON CONFLICT (code) DO NOTHING;

SELECT setval(pg_get_serial_sequence('mbti_types', 'id'), (SELECT COALESCE(MAX(id), 1) FROM mbti_types));
